package com.dfoda.dex.codigo;

import com.dfoda.dex.DexOptions;
import com.dfoda.dex.codigo.Dop;
import com.dfoda.dex.codigo.forma.Form10t;
import com.dfoda.dex.codigo.forma.Form10x;
import com.dfoda.dex.codigo.forma.Form11n;
import com.dfoda.dex.codigo.forma.Form11x;
import com.dfoda.dex.codigo.forma.Form12x;
import com.dfoda.dex.codigo.forma.Form20t;
import com.dfoda.dex.codigo.forma.Form21c;
import com.dfoda.dex.codigo.forma.Form21h;
import com.dfoda.dex.codigo.forma.Form21s;
import com.dfoda.dex.codigo.forma.Form21t;
import com.dfoda.dex.codigo.forma.Form22b;
import com.dfoda.dex.codigo.forma.Form22c;
import com.dfoda.dex.codigo.forma.Form22s;
import com.dfoda.dex.codigo.forma.Form22t;
import com.dfoda.dex.codigo.forma.Form22x;
import com.dfoda.dex.codigo.forma.Form23x;
import com.dfoda.dex.codigo.forma.Form30t;
import com.dfoda.dex.codigo.forma.Form31c;
import com.dfoda.dex.codigo.forma.Form31i;
import com.dfoda.dex.codigo.forma.Form31t;
import com.dfoda.dex.codigo.forma.Form32x;
import com.dfoda.dex.codigo.forma.Form35c;
import com.dfoda.dex.codigo.forma.Form3rc;
import com.dfoda.dex.codigo.forma.Form45cc;
import com.dfoda.dex.codigo.forma.Form4rcc;
import com.dfoda.dex.codigo.forma.Form51l;
import com.dfoda.dex.codigo.forma.SpecialFormat;

public final class Dops {
    private static final Dop[] DOPS;
    public static final Dop SPECIAL_FORMAT;
    public static final Dop NOP;
    public static final Dop MOVE;
    public static final Dop MOVE_FROM16;
    public static final Dop MOVE_16;
    public static final Dop MOVE_WIDE;
    public static final Dop MOVE_WIDE_FROM16;
    public static final Dop MOVE_WIDE_16;
    public static final Dop MOVE_OBJECT;
    public static final Dop MOVE_OBJECT_FROM16;
    public static final Dop MOVE_OBJECT_16;
    public static final Dop MOVE_RESULT;
    public static final Dop MOVE_RESULT_WIDE;
    public static final Dop MOVE_RESULT_OBJECT;
    public static final Dop MOVE_EXCEPTION;
    public static final Dop RETURN_VOID;
    public static final Dop RETURN;
    public static final Dop RETURN_WIDE;
    public static final Dop RETURN_OBJECT;
    public static final Dop CONST_4;
    public static final Dop CONST_16;
    public static final Dop CONST;
    public static final Dop CONST_HIGH16;
    public static final Dop CONST_WIDE_16;
    public static final Dop CONST_WIDE_32;
    public static final Dop CONST_WIDE;
    public static final Dop CONST_WIDE_HIGH16;
    public static final Dop CONST_STRING;
    public static final Dop CONST_STRING_JUMBO;
    public static final Dop CONST_CLASS;
    public static final Dop MONITOR_ENTER;
    public static final Dop MONITOR_EXIT;
    public static final Dop CHECK_CAST;
    public static final Dop INSTANCE_OF;
    public static final Dop ARRAY_LENGTH;
    public static final Dop NEW_INSTANCE;
    public static final Dop NEW_ARRAY;
    public static final Dop FILLED_NEW_ARRAY;
    public static final Dop FILLED_NEW_ARRAY_RANGE;
    public static final Dop FILL_ARRAY_DATA;
    public static final Dop THROW;
    public static final Dop GOTO;
    public static final Dop GOTO_16;
    public static final Dop GOTO_32;
    public static final Dop PACKED_SWITCH;
    public static final Dop SPARSE_SWITCH;
    public static final Dop CMPL_FLOAT;
    public static final Dop CMPG_FLOAT;
    public static final Dop CMPL_DOUBLE;
    public static final Dop CMPG_DOUBLE;
    public static final Dop CMP_LONG;
    public static final Dop IF_EQ;
    public static final Dop IF_NE;
    public static final Dop IF_LT;
    public static final Dop IF_GE;
    public static final Dop IF_GT;
    public static final Dop IF_LE;
    public static final Dop IF_EQZ;
    public static final Dop IF_NEZ;
    public static final Dop IF_LTZ;
    public static final Dop IF_GEZ;
    public static final Dop IF_GTZ;
    public static final Dop IF_LEZ;
    public static final Dop AGET;
    public static final Dop AGET_WIDE;
    public static final Dop AGET_OBJECT;
    public static final Dop AGET_BOOLEAN;
    public static final Dop AGET_BYTE;
    public static final Dop AGET_CHAR;
    public static final Dop AGET_SHORT;
    public static final Dop APUT;
    public static final Dop APUT_WIDE;
    public static final Dop APUT_OBJECT;
    public static final Dop APUT_BOOLEAN;
    public static final Dop APUT_BYTE;
    public static final Dop APUT_CHAR;
    public static final Dop APUT_SHORT;
    public static final Dop IGET;
    public static final Dop IGET_WIDE;
    public static final Dop IGET_OBJECT;
    public static final Dop IGET_BOOLEAN;
    public static final Dop IGET_BYTE;
    public static final Dop IGET_CHAR;
    public static final Dop IGET_SHORT;
    public static final Dop IPUT;
    public static final Dop IPUT_WIDE;
    public static final Dop IPUT_OBJECT;
    public static final Dop IPUT_BOOLEAN;
    public static final Dop IPUT_BYTE;
    public static final Dop IPUT_CHAR;
    public static final Dop IPUT_SHORT;
    public static final Dop SGET;
    public static final Dop SGET_WIDE;
    public static final Dop SGET_OBJECT;
    public static final Dop SGET_BOOLEAN;
    public static final Dop SGET_BYTE;
    public static final Dop SGET_CHAR;
    public static final Dop SGET_SHORT;
    public static final Dop SPUT;
    public static final Dop SPUT_WIDE;
    public static final Dop SPUT_OBJECT;
    public static final Dop SPUT_BOOLEAN;
    public static final Dop SPUT_BYTE;
    public static final Dop SPUT_CHAR;
    public static final Dop SPUT_SHORT;
    public static final Dop INVOKE_VIRTUAL;
    public static final Dop INVOKE_SUPER;
    public static final Dop INVOKE_DIRECT;
    public static final Dop INVOKE_STATIC;
    public static final Dop INVOKE_INTERFACE;
    public static final Dop INVOKE_VIRTUAL_RANGE;
    public static final Dop INVOKE_SUPER_RANGE;
    public static final Dop INVOKE_DIRECT_RANGE;
    public static final Dop INVOKE_STATIC_RANGE;
    public static final Dop INVOKE_INTERFACE_RANGE;
    public static final Dop NEG_INT;
    public static final Dop NOT_INT;
    public static final Dop NEG_LONG;
    public static final Dop NOT_LONG;
    public static final Dop NEG_FLOAT;
    public static final Dop NEG_DOUBLE;
    public static final Dop INT_TO_LONG;
    public static final Dop INT_TO_FLOAT;
    public static final Dop INT_TO_DOUBLE;
    public static final Dop LONG_TO_INT;
    public static final Dop LONG_TO_FLOAT;
    public static final Dop LONG_TO_DOUBLE;
    public static final Dop FLOAT_TO_INT;
    public static final Dop FLOAT_TO_LONG;
    public static final Dop FLOAT_TO_DOUBLE;
    public static final Dop DOUBLE_TO_INT;
    public static final Dop DOUBLE_TO_LONG;
    public static final Dop DOUBLE_TO_FLOAT;
    public static final Dop INT_TO_BYTE;
    public static final Dop INT_TO_CHAR;
    public static final Dop INT_TO_SHORT;
    public static final Dop ADD_INT;
    public static final Dop SUB_INT;
    public static final Dop MUL_INT;
    public static final Dop DIV_INT;
    public static final Dop REM_INT;
    public static final Dop AND_INT;
    public static final Dop OR_INT;
    public static final Dop XOR_INT;
    public static final Dop SHL_INT;
    public static final Dop SHR_INT;
    public static final Dop USHR_INT;
    public static final Dop ADD_LONG;
    public static final Dop SUB_LONG;
    public static final Dop MUL_LONG;
    public static final Dop DIV_LONG;
    public static final Dop REM_LONG;
    public static final Dop AND_LONG;
    public static final Dop OR_LONG;
    public static final Dop XOR_LONG;
    public static final Dop SHL_LONG;
    public static final Dop SHR_LONG;
    public static final Dop USHR_LONG;
    public static final Dop ADD_FLOAT;
    public static final Dop SUB_FLOAT;
    public static final Dop MUL_FLOAT;
    public static final Dop DIV_FLOAT;
    public static final Dop REM_FLOAT;
    public static final Dop ADD_DOUBLE;
    public static final Dop SUB_DOUBLE;
    public static final Dop MUL_DOUBLE;
    public static final Dop DIV_DOUBLE;
    public static final Dop REM_DOUBLE;
    public static final Dop ADD_INT_2ADDR;
    public static final Dop SUB_INT_2ADDR;
    public static final Dop MUL_INT_2ADDR;
    public static final Dop DIV_INT_2ADDR;
    public static final Dop REM_INT_2ADDR;
    public static final Dop AND_INT_2ADDR;
    public static final Dop OR_INT_2ADDR;
    public static final Dop XOR_INT_2ADDR;
    public static final Dop SHL_INT_2ADDR;
    public static final Dop SHR_INT_2ADDR;
    public static final Dop USHR_INT_2ADDR;
    public static final Dop ADD_LONG_2ADDR;
    public static final Dop SUB_LONG_2ADDR;
    public static final Dop MUL_LONG_2ADDR;
    public static final Dop DIV_LONG_2ADDR;
    public static final Dop REM_LONG_2ADDR;
    public static final Dop AND_LONG_2ADDR;
    public static final Dop OR_LONG_2ADDR;
    public static final Dop XOR_LONG_2ADDR;
    public static final Dop SHL_LONG_2ADDR;
    public static final Dop SHR_LONG_2ADDR;
    public static final Dop USHR_LONG_2ADDR;
    public static final Dop ADD_FLOAT_2ADDR;
    public static final Dop SUB_FLOAT_2ADDR;
    public static final Dop MUL_FLOAT_2ADDR;
    public static final Dop DIV_FLOAT_2ADDR;
    public static final Dop REM_FLOAT_2ADDR;
    public static final Dop ADD_DOUBLE_2ADDR;
    public static final Dop SUB_DOUBLE_2ADDR;
    public static final Dop MUL_DOUBLE_2ADDR;
    public static final Dop DIV_DOUBLE_2ADDR;
    public static final Dop REM_DOUBLE_2ADDR;
    public static final Dop ADD_INT_LIT16;
    public static final Dop RSUB_INT;
    public static final Dop MUL_INT_LIT16;
    public static final Dop DIV_INT_LIT16;
    public static final Dop REM_INT_LIT16;
    public static final Dop AND_INT_LIT16;
    public static final Dop OR_INT_LIT16;
    public static final Dop XOR_INT_LIT16;
    public static final Dop ADD_INT_LIT8;
    public static final Dop RSUB_INT_LIT8;
    public static final Dop MUL_INT_LIT8;
    public static final Dop DIV_INT_LIT8;
    public static final Dop REM_INT_LIT8;
    public static final Dop AND_INT_LIT8;
    public static final Dop OR_INT_LIT8;
    public static final Dop XOR_INT_LIT8;
    public static final Dop SHL_INT_LIT8;
    public static final Dop SHR_INT_LIT8;
    public static final Dop USHR_INT_LIT8;
    public static final Dop INVOKE_POLYMORPHIC;
    public static final Dop INVOKE_POLYMORPHIC_RANGE;
    public static final Dop INVOKE_CUSTOM;
    public static final Dop INVOKE_CUSTOM_RANGE;
    public static final Dop CONST_METHOD_HANDLE;
    public static final Dop CONST_METHOD_TYPE;

    private Dops() {
    }

    public static Dop get(int opcode) {
        int idx = opcode - -1;
        try {
            Dop result = DOPS[idx];
            if (result != null) {
                return result;
            }
        }
        catch (ArrayIndexOutOfBoundsException arrayIndexOutOfBoundsException) {
            // empty catch block
        }
        throw new IllegalArgumentException("bogus opcode");
    }

    public static Dop getNextOrNull(Dop opcode, DexOptions options) {
        int nextOpcode = opcode.getNextOpcode();
        if (nextOpcode == -1) {
            return null;
        }
        opcode = Dops.get(nextOpcode);
        return opcode;
    }

    private static void set(Dop opcode) {
        int idx = opcode.getOpcode() - -1;
        Dops.DOPS[idx] = opcode;
    }

    static {
        SPECIAL_FORMAT = new Dop(-1, -1, -1, SpecialFormat.THE_ONE, false);
        NOP = new Dop(0, 0, -1, Form10x.THE_ONE, false);
        MOVE = new Dop(1, 1, 2, Form12x.THE_ONE, true);
        MOVE_FROM16 = new Dop(2, 1, 3, Form22x.THE_ONE, true);
        MOVE_16 = new Dop(3, 1, -1, Form32x.THE_ONE, true);
        MOVE_WIDE = new Dop(4, 4, 5, Form12x.THE_ONE, true);
        MOVE_WIDE_FROM16 = new Dop(5, 4, 6, Form22x.THE_ONE, true);
        MOVE_WIDE_16 = new Dop(6, 4, -1, Form32x.THE_ONE, true);
        MOVE_OBJECT = new Dop(7, 7, 8, Form12x.THE_ONE, true);
        MOVE_OBJECT_FROM16 = new Dop(8, 7, 9, Form22x.THE_ONE, true);
        MOVE_OBJECT_16 = new Dop(9, 7, -1, Form32x.THE_ONE, true);
        MOVE_RESULT = new Dop(10, 10, -1, Form11x.THE_ONE, true);
        MOVE_RESULT_WIDE = new Dop(11, 11, -1, Form11x.THE_ONE, true);
        MOVE_RESULT_OBJECT = new Dop(12, 12, -1, Form11x.THE_ONE, true);
        MOVE_EXCEPTION = new Dop(13, 13, -1, Form11x.THE_ONE, true);
        RETURN_VOID = new Dop(14, 14, -1, Form10x.THE_ONE, false);
        RETURN = new Dop(15, 15, -1, Form11x.THE_ONE, false);
        RETURN_WIDE = new Dop(16, 16, -1, Form11x.THE_ONE, false);
        RETURN_OBJECT = new Dop(17, 17, -1, Form11x.THE_ONE, false);
        CONST_4 = new Dop(18, 20, 19, Form11n.THE_ONE, true);
        CONST_16 = new Dop(19, 20, 21, Form21s.THE_ONE, true);
        CONST = new Dop(20, 20, -1, Form31i.THE_ONE, true);
        CONST_HIGH16 = new Dop(21, 20, 20, Form21h.THE_ONE, true);
        CONST_WIDE_16 = new Dop(22, 24, 25, Form21s.THE_ONE, true);
        CONST_WIDE_32 = new Dop(23, 24, 24, Form31i.THE_ONE, true);
        CONST_WIDE = new Dop(24, 24, -1, Form51l.THE_ONE, true);
        CONST_WIDE_HIGH16 = new Dop(25, 24, 23, Form21h.THE_ONE, true);
        CONST_STRING = new Dop(26, 26, 27, Form21c.THE_ONE, true);
        CONST_STRING_JUMBO = new Dop(27, 26, -1, Form31c.THE_ONE, true);
        CONST_CLASS = new Dop(28, 28, -1, Form21c.THE_ONE, true);
        MONITOR_ENTER = new Dop(29, 29, -1, Form11x.THE_ONE, false);
        MONITOR_EXIT = new Dop(30, 30, -1, Form11x.THE_ONE, false);
        CHECK_CAST = new Dop(31, 31, -1, Form21c.THE_ONE, true);
        INSTANCE_OF = new Dop(32, 32, -1, Form22c.THE_ONE, true);
        ARRAY_LENGTH = new Dop(33, 33, -1, Form12x.THE_ONE, true);
        NEW_INSTANCE = new Dop(34, 34, -1, Form21c.THE_ONE, true);
        NEW_ARRAY = new Dop(35, 35, -1, Form22c.THE_ONE, true);
        FILLED_NEW_ARRAY = new Dop(36, 36, 37, Form35c.THE_ONE, false);
        FILLED_NEW_ARRAY_RANGE = new Dop(37, 36, -1, Form3rc.THE_ONE, false);
        FILL_ARRAY_DATA = new Dop(38, 38, -1, Form31t.THE_ONE, false);
        THROW = new Dop(39, 39, -1, Form11x.THE_ONE, false);
        GOTO = new Dop(40, 40, 41, Form10t.THE_ONE, false);
        GOTO_16 = new Dop(41, 40, 42, Form20t.THE_ONE, false);
        GOTO_32 = new Dop(42, 40, -1, Form30t.THE_ONE, false);
        PACKED_SWITCH = new Dop(43, 43, -1, Form31t.THE_ONE, false);
        SPARSE_SWITCH = new Dop(44, 44, -1, Form31t.THE_ONE, false);
        CMPL_FLOAT = new Dop(45, 45, -1, Form23x.THE_ONE, true);
        CMPG_FLOAT = new Dop(46, 46, -1, Form23x.THE_ONE, true);
        CMPL_DOUBLE = new Dop(47, 47, -1, Form23x.THE_ONE, true);
        CMPG_DOUBLE = new Dop(48, 48, -1, Form23x.THE_ONE, true);
        CMP_LONG = new Dop(49, 49, -1, Form23x.THE_ONE, true);
        IF_EQ = new Dop(50, 50, -1, Form22t.THE_ONE, false);
        IF_NE = new Dop(51, 51, -1, Form22t.THE_ONE, false);
        IF_LT = new Dop(52, 52, -1, Form22t.THE_ONE, false);
        IF_GE = new Dop(53, 53, -1, Form22t.THE_ONE, false);
        IF_GT = new Dop(54, 54, -1, Form22t.THE_ONE, false);
        IF_LE = new Dop(55, 55, -1, Form22t.THE_ONE, false);
        IF_EQZ = new Dop(56, 56, -1, Form21t.THE_ONE, false);
        IF_NEZ = new Dop(57, 57, -1, Form21t.THE_ONE, false);
        IF_LTZ = new Dop(58, 58, -1, Form21t.THE_ONE, false);
        IF_GEZ = new Dop(59, 59, -1, Form21t.THE_ONE, false);
        IF_GTZ = new Dop(60, 60, -1, Form21t.THE_ONE, false);
        IF_LEZ = new Dop(61, 61, -1, Form21t.THE_ONE, false);
        AGET = new Dop(68, 68, -1, Form23x.THE_ONE, true);
        AGET_WIDE = new Dop(69, 69, -1, Form23x.THE_ONE, true);
        AGET_OBJECT = new Dop(70, 70, -1, Form23x.THE_ONE, true);
        AGET_BOOLEAN = new Dop(71, 71, -1, Form23x.THE_ONE, true);
        AGET_BYTE = new Dop(72, 72, -1, Form23x.THE_ONE, true);
        AGET_CHAR = new Dop(73, 73, -1, Form23x.THE_ONE, true);
        AGET_SHORT = new Dop(74, 74, -1, Form23x.THE_ONE, true);
        APUT = new Dop(75, 75, -1, Form23x.THE_ONE, false);
        APUT_WIDE = new Dop(76, 76, -1, Form23x.THE_ONE, false);
        APUT_OBJECT = new Dop(77, 77, -1, Form23x.THE_ONE, false);
        APUT_BOOLEAN = new Dop(78, 78, -1, Form23x.THE_ONE, false);
        APUT_BYTE = new Dop(79, 79, -1, Form23x.THE_ONE, false);
        APUT_CHAR = new Dop(80, 80, -1, Form23x.THE_ONE, false);
        APUT_SHORT = new Dop(81, 81, -1, Form23x.THE_ONE, false);
        IGET = new Dop(82, 82, -1, Form22c.THE_ONE, true);
        IGET_WIDE = new Dop(83, 83, -1, Form22c.THE_ONE, true);
        IGET_OBJECT = new Dop(84, 84, -1, Form22c.THE_ONE, true);
        IGET_BOOLEAN = new Dop(85, 85, -1, Form22c.THE_ONE, true);
        IGET_BYTE = new Dop(86, 86, -1, Form22c.THE_ONE, true);
        IGET_CHAR = new Dop(87, 87, -1, Form22c.THE_ONE, true);
        IGET_SHORT = new Dop(88, 88, -1, Form22c.THE_ONE, true);
        IPUT = new Dop(89, 89, -1, Form22c.THE_ONE, false);
        IPUT_WIDE = new Dop(90, 90, -1, Form22c.THE_ONE, false);
        IPUT_OBJECT = new Dop(91, 91, -1, Form22c.THE_ONE, false);
        IPUT_BOOLEAN = new Dop(92, 92, -1, Form22c.THE_ONE, false);
        IPUT_BYTE = new Dop(93, 93, -1, Form22c.THE_ONE, false);
        IPUT_CHAR = new Dop(94, 94, -1, Form22c.THE_ONE, false);
        IPUT_SHORT = new Dop(95, 95, -1, Form22c.THE_ONE, false);
        SGET = new Dop(96, 96, -1, Form21c.THE_ONE, true);
        SGET_WIDE = new Dop(97, 97, -1, Form21c.THE_ONE, true);
        SGET_OBJECT = new Dop(98, 98, -1, Form21c.THE_ONE, true);
        SGET_BOOLEAN = new Dop(99, 99, -1, Form21c.THE_ONE, true);
        SGET_BYTE = new Dop(100, 100, -1, Form21c.THE_ONE, true);
        SGET_CHAR = new Dop(101, 101, -1, Form21c.THE_ONE, true);
        SGET_SHORT = new Dop(102, 102, -1, Form21c.THE_ONE, true);
        SPUT = new Dop(103, 103, -1, Form21c.THE_ONE, false);
        SPUT_WIDE = new Dop(104, 104, -1, Form21c.THE_ONE, false);
        SPUT_OBJECT = new Dop(105, 105, -1, Form21c.THE_ONE, false);
        SPUT_BOOLEAN = new Dop(106, 106, -1, Form21c.THE_ONE, false);
        SPUT_BYTE = new Dop(107, 107, -1, Form21c.THE_ONE, false);
        SPUT_CHAR = new Dop(108, 108, -1, Form21c.THE_ONE, false);
        SPUT_SHORT = new Dop(109, 109, -1, Form21c.THE_ONE, false);
        INVOKE_VIRTUAL = new Dop(110, 110, 116, Form35c.THE_ONE, false);
        INVOKE_SUPER = new Dop(111, 111, 117, Form35c.THE_ONE, false);
        INVOKE_DIRECT = new Dop(112, 112, 118, Form35c.THE_ONE, false);
        INVOKE_STATIC = new Dop(113, 113, 119, Form35c.THE_ONE, false);
        INVOKE_INTERFACE = new Dop(114, 114, 120, Form35c.THE_ONE, false);
        INVOKE_VIRTUAL_RANGE = new Dop(116, 110, -1, Form3rc.THE_ONE, false);
        INVOKE_SUPER_RANGE = new Dop(117, 111, -1, Form3rc.THE_ONE, false);
        INVOKE_DIRECT_RANGE = new Dop(118, 112, -1, Form3rc.THE_ONE, false);
        INVOKE_STATIC_RANGE = new Dop(119, 113, -1, Form3rc.THE_ONE, false);
        INVOKE_INTERFACE_RANGE = new Dop(120, 114, -1, Form3rc.THE_ONE, false);
        NEG_INT = new Dop(123, 123, -1, Form12x.THE_ONE, true);
        NOT_INT = new Dop(124, 124, -1, Form12x.THE_ONE, true);
        NEG_LONG = new Dop(125, 125, -1, Form12x.THE_ONE, true);
        NOT_LONG = new Dop(126, 126, -1, Form12x.THE_ONE, true);
        NEG_FLOAT = new Dop(127, 127, -1, Form12x.THE_ONE, true);
        NEG_DOUBLE = new Dop(128, 128, -1, Form12x.THE_ONE, true);
        INT_TO_LONG = new Dop(129, 129, -1, Form12x.THE_ONE, true);
        INT_TO_FLOAT = new Dop(130, 130, -1, Form12x.THE_ONE, true);
        INT_TO_DOUBLE = new Dop(131, 131, -1, Form12x.THE_ONE, true);
        LONG_TO_INT = new Dop(132, 132, -1, Form12x.THE_ONE, true);
        LONG_TO_FLOAT = new Dop(133, 133, -1, Form12x.THE_ONE, true);
        LONG_TO_DOUBLE = new Dop(134, 134, -1, Form12x.THE_ONE, true);
        FLOAT_TO_INT = new Dop(135, 135, -1, Form12x.THE_ONE, true);
        FLOAT_TO_LONG = new Dop(136, 136, -1, Form12x.THE_ONE, true);
        FLOAT_TO_DOUBLE = new Dop(137, 137, -1, Form12x.THE_ONE, true);
        DOUBLE_TO_INT = new Dop(138, 138, -1, Form12x.THE_ONE, true);
        DOUBLE_TO_LONG = new Dop(139, 139, -1, Form12x.THE_ONE, true);
        DOUBLE_TO_FLOAT = new Dop(140, 140, -1, Form12x.THE_ONE, true);
        INT_TO_BYTE = new Dop(141, 141, -1, Form12x.THE_ONE, true);
        INT_TO_CHAR = new Dop(142, 142, -1, Form12x.THE_ONE, true);
        INT_TO_SHORT = new Dop(143, 143, -1, Form12x.THE_ONE, true);
        ADD_INT = new Dop(144, 144, -1, Form23x.THE_ONE, true);
        SUB_INT = new Dop(145, 145, -1, Form23x.THE_ONE, true);
        MUL_INT = new Dop(146, 146, -1, Form23x.THE_ONE, true);
        DIV_INT = new Dop(147, 147, -1, Form23x.THE_ONE, true);
        REM_INT = new Dop(148, 148, -1, Form23x.THE_ONE, true);
        AND_INT = new Dop(149, 149, -1, Form23x.THE_ONE, true);
        OR_INT = new Dop(150, 150, -1, Form23x.THE_ONE, true);
        XOR_INT = new Dop(151, 151, -1, Form23x.THE_ONE, true);
        SHL_INT = new Dop(152, 152, -1, Form23x.THE_ONE, true);
        SHR_INT = new Dop(153, 153, -1, Form23x.THE_ONE, true);
        USHR_INT = new Dop(154, 154, -1, Form23x.THE_ONE, true);
        ADD_LONG = new Dop(155, 155, -1, Form23x.THE_ONE, true);
        SUB_LONG = new Dop(156, 156, -1, Form23x.THE_ONE, true);
        MUL_LONG = new Dop(157, 157, -1, Form23x.THE_ONE, true);
        DIV_LONG = new Dop(158, 158, -1, Form23x.THE_ONE, true);
        REM_LONG = new Dop(159, 159, -1, Form23x.THE_ONE, true);
        AND_LONG = new Dop(160, 160, -1, Form23x.THE_ONE, true);
        OR_LONG = new Dop(161, 161, -1, Form23x.THE_ONE, true);
        XOR_LONG = new Dop(162, 162, -1, Form23x.THE_ONE, true);
        SHL_LONG = new Dop(163, 163, -1, Form23x.THE_ONE, true);
        SHR_LONG = new Dop(164, 164, -1, Form23x.THE_ONE, true);
        USHR_LONG = new Dop(165, 165, -1, Form23x.THE_ONE, true);
        ADD_FLOAT = new Dop(166, 166, -1, Form23x.THE_ONE, true);
        SUB_FLOAT = new Dop(167, 167, -1, Form23x.THE_ONE, true);
        MUL_FLOAT = new Dop(168, 168, -1, Form23x.THE_ONE, true);
        DIV_FLOAT = new Dop(169, 169, -1, Form23x.THE_ONE, true);
        REM_FLOAT = new Dop(170, 170, -1, Form23x.THE_ONE, true);
        ADD_DOUBLE = new Dop(171, 171, -1, Form23x.THE_ONE, true);
        SUB_DOUBLE = new Dop(172, 172, -1, Form23x.THE_ONE, true);
        MUL_DOUBLE = new Dop(173, 173, -1, Form23x.THE_ONE, true);
        DIV_DOUBLE = new Dop(174, 174, -1, Form23x.THE_ONE, true);
        REM_DOUBLE = new Dop(175, 175, -1, Form23x.THE_ONE, true);
        ADD_INT_2ADDR = new Dop(176, 144, 144, Form12x.THE_ONE, true);
        SUB_INT_2ADDR = new Dop(177, 145, 145, Form12x.THE_ONE, true);
        MUL_INT_2ADDR = new Dop(178, 146, 146, Form12x.THE_ONE, true);
        DIV_INT_2ADDR = new Dop(179, 147, 147, Form12x.THE_ONE, true);
        REM_INT_2ADDR = new Dop(180, 148, 148, Form12x.THE_ONE, true);
        AND_INT_2ADDR = new Dop(181, 149, 149, Form12x.THE_ONE, true);
        OR_INT_2ADDR = new Dop(182, 150, 150, Form12x.THE_ONE, true);
        XOR_INT_2ADDR = new Dop(183, 151, 151, Form12x.THE_ONE, true);
        SHL_INT_2ADDR = new Dop(184, 152, 152, Form12x.THE_ONE, true);
        SHR_INT_2ADDR = new Dop(185, 153, 153, Form12x.THE_ONE, true);
        USHR_INT_2ADDR = new Dop(186, 154, 154, Form12x.THE_ONE, true);
        ADD_LONG_2ADDR = new Dop(187, 155, 155, Form12x.THE_ONE, true);
        SUB_LONG_2ADDR = new Dop(188, 156, 156, Form12x.THE_ONE, true);
        MUL_LONG_2ADDR = new Dop(189, 157, 157, Form12x.THE_ONE, true);
        DIV_LONG_2ADDR = new Dop(190, 158, 158, Form12x.THE_ONE, true);
        REM_LONG_2ADDR = new Dop(191, 159, 159, Form12x.THE_ONE, true);
        AND_LONG_2ADDR = new Dop(192, 160, 160, Form12x.THE_ONE, true);
        OR_LONG_2ADDR = new Dop(193, 161, 161, Form12x.THE_ONE, true);
        XOR_LONG_2ADDR = new Dop(194, 162, 162, Form12x.THE_ONE, true);
        SHL_LONG_2ADDR = new Dop(195, 163, 163, Form12x.THE_ONE, true);
        SHR_LONG_2ADDR = new Dop(196, 164, 164, Form12x.THE_ONE, true);
        USHR_LONG_2ADDR = new Dop(197, 165, 165, Form12x.THE_ONE, true);
        ADD_FLOAT_2ADDR = new Dop(198, 166, 166, Form12x.THE_ONE, true);
        SUB_FLOAT_2ADDR = new Dop(199, 167, 167, Form12x.THE_ONE, true);
        MUL_FLOAT_2ADDR = new Dop(200, 168, 168, Form12x.THE_ONE, true);
        DIV_FLOAT_2ADDR = new Dop(201, 169, 169, Form12x.THE_ONE, true);
        REM_FLOAT_2ADDR = new Dop(202, 170, 170, Form12x.THE_ONE, true);
        ADD_DOUBLE_2ADDR = new Dop(203, 171, 171, Form12x.THE_ONE, true);
        SUB_DOUBLE_2ADDR = new Dop(204, 172, 172, Form12x.THE_ONE, true);
        MUL_DOUBLE_2ADDR = new Dop(205, 173, 173, Form12x.THE_ONE, true);
        DIV_DOUBLE_2ADDR = new Dop(206, 174, 174, Form12x.THE_ONE, true);
        REM_DOUBLE_2ADDR = new Dop(207, 175, 175, Form12x.THE_ONE, true);
        ADD_INT_LIT16 = new Dop(208, 144, -1, Form22s.THE_ONE, true);
        RSUB_INT = new Dop(209, 209, -1, Form22s.THE_ONE, true);
        MUL_INT_LIT16 = new Dop(210, 146, -1, Form22s.THE_ONE, true);
        DIV_INT_LIT16 = new Dop(211, 147, -1, Form22s.THE_ONE, true);
        REM_INT_LIT16 = new Dop(212, 148, -1, Form22s.THE_ONE, true);
        AND_INT_LIT16 = new Dop(213, 149, -1, Form22s.THE_ONE, true);
        OR_INT_LIT16 = new Dop(214, 150, -1, Form22s.THE_ONE, true);
        XOR_INT_LIT16 = new Dop(215, 151, -1, Form22s.THE_ONE, true);
        ADD_INT_LIT8 = new Dop(216, 144, 208, Form22b.THE_ONE, true);
        RSUB_INT_LIT8 = new Dop(217, 209, 209, Form22b.THE_ONE, true);
        MUL_INT_LIT8 = new Dop(218, 146, 210, Form22b.THE_ONE, true);
        DIV_INT_LIT8 = new Dop(219, 147, 211, Form22b.THE_ONE, true);
        REM_INT_LIT8 = new Dop(220, 148, 212, Form22b.THE_ONE, true);
        AND_INT_LIT8 = new Dop(221, 149, 213, Form22b.THE_ONE, true);
        OR_INT_LIT8 = new Dop(222, 150, 214, Form22b.THE_ONE, true);
        XOR_INT_LIT8 = new Dop(223, 151, 215, Form22b.THE_ONE, true);
        SHL_INT_LIT8 = new Dop(224, 152, -1, Form22b.THE_ONE, true);
        SHR_INT_LIT8 = new Dop(225, 153, -1, Form22b.THE_ONE, true);
        USHR_INT_LIT8 = new Dop(226, 154, -1, Form22b.THE_ONE, true);
        INVOKE_POLYMORPHIC = new Dop(250, 250, 251, Form45cc.THE_ONE, false);
        INVOKE_POLYMORPHIC_RANGE = new Dop(251, 250, -1, Form4rcc.THE_ONE, false);
        INVOKE_CUSTOM = new Dop(252, 252, 253, Form35c.THE_ONE, false);
        INVOKE_CUSTOM_RANGE = new Dop(253, 252, -1, Form3rc.THE_ONE, false);
        CONST_METHOD_HANDLE = new Dop(254, 254, -1, Form21c.THE_ONE, true);
        CONST_METHOD_TYPE = new Dop(255, 255, -1, Form21c.THE_ONE, true);
        DOPS = new Dop[65537];
        Dops.set(SPECIAL_FORMAT);
        Dops.set(NOP);
        Dops.set(MOVE);
        Dops.set(MOVE_FROM16);
        Dops.set(MOVE_16);
        Dops.set(MOVE_WIDE);
        Dops.set(MOVE_WIDE_FROM16);
        Dops.set(MOVE_WIDE_16);
        Dops.set(MOVE_OBJECT);
        Dops.set(MOVE_OBJECT_FROM16);
        Dops.set(MOVE_OBJECT_16);
        Dops.set(MOVE_RESULT);
        Dops.set(MOVE_RESULT_WIDE);
        Dops.set(MOVE_RESULT_OBJECT);
        Dops.set(MOVE_EXCEPTION);
        Dops.set(RETURN_VOID);
        Dops.set(RETURN);
        Dops.set(RETURN_WIDE);
        Dops.set(RETURN_OBJECT);
        Dops.set(CONST_4);
        Dops.set(CONST_16);
        Dops.set(CONST);
        Dops.set(CONST_HIGH16);
        Dops.set(CONST_WIDE_16);
        Dops.set(CONST_WIDE_32);
        Dops.set(CONST_WIDE);
        Dops.set(CONST_WIDE_HIGH16);
        Dops.set(CONST_STRING);
        Dops.set(CONST_STRING_JUMBO);
        Dops.set(CONST_CLASS);
        Dops.set(MONITOR_ENTER);
        Dops.set(MONITOR_EXIT);
        Dops.set(CHECK_CAST);
        Dops.set(INSTANCE_OF);
        Dops.set(ARRAY_LENGTH);
        Dops.set(NEW_INSTANCE);
        Dops.set(NEW_ARRAY);
        Dops.set(FILLED_NEW_ARRAY);
        Dops.set(FILLED_NEW_ARRAY_RANGE);
        Dops.set(FILL_ARRAY_DATA);
        Dops.set(THROW);
        Dops.set(GOTO);
        Dops.set(GOTO_16);
        Dops.set(GOTO_32);
        Dops.set(PACKED_SWITCH);
        Dops.set(SPARSE_SWITCH);
        Dops.set(CMPL_FLOAT);
        Dops.set(CMPG_FLOAT);
        Dops.set(CMPL_DOUBLE);
        Dops.set(CMPG_DOUBLE);
        Dops.set(CMP_LONG);
        Dops.set(IF_EQ);
        Dops.set(IF_NE);
        Dops.set(IF_LT);
        Dops.set(IF_GE);
        Dops.set(IF_GT);
        Dops.set(IF_LE);
        Dops.set(IF_EQZ);
        Dops.set(IF_NEZ);
        Dops.set(IF_LTZ);
        Dops.set(IF_GEZ);
        Dops.set(IF_GTZ);
        Dops.set(IF_LEZ);
        Dops.set(AGET);
        Dops.set(AGET_WIDE);
        Dops.set(AGET_OBJECT);
        Dops.set(AGET_BOOLEAN);
        Dops.set(AGET_BYTE);
        Dops.set(AGET_CHAR);
        Dops.set(AGET_SHORT);
        Dops.set(APUT);
        Dops.set(APUT_WIDE);
        Dops.set(APUT_OBJECT);
        Dops.set(APUT_BOOLEAN);
        Dops.set(APUT_BYTE);
        Dops.set(APUT_CHAR);
        Dops.set(APUT_SHORT);
        Dops.set(IGET);
        Dops.set(IGET_WIDE);
        Dops.set(IGET_OBJECT);
        Dops.set(IGET_BOOLEAN);
        Dops.set(IGET_BYTE);
        Dops.set(IGET_CHAR);
        Dops.set(IGET_SHORT);
        Dops.set(IPUT);
        Dops.set(IPUT_WIDE);
        Dops.set(IPUT_OBJECT);
        Dops.set(IPUT_BOOLEAN);
        Dops.set(IPUT_BYTE);
        Dops.set(IPUT_CHAR);
        Dops.set(IPUT_SHORT);
        Dops.set(SGET);
        Dops.set(SGET_WIDE);
        Dops.set(SGET_OBJECT);
        Dops.set(SGET_BOOLEAN);
        Dops.set(SGET_BYTE);
        Dops.set(SGET_CHAR);
        Dops.set(SGET_SHORT);
        Dops.set(SPUT);
        Dops.set(SPUT_WIDE);
        Dops.set(SPUT_OBJECT);
        Dops.set(SPUT_BOOLEAN);
        Dops.set(SPUT_BYTE);
        Dops.set(SPUT_CHAR);
        Dops.set(SPUT_SHORT);
        Dops.set(INVOKE_VIRTUAL);
        Dops.set(INVOKE_SUPER);
        Dops.set(INVOKE_DIRECT);
        Dops.set(INVOKE_STATIC);
        Dops.set(INVOKE_INTERFACE);
        Dops.set(INVOKE_VIRTUAL_RANGE);
        Dops.set(INVOKE_SUPER_RANGE);
        Dops.set(INVOKE_DIRECT_RANGE);
        Dops.set(INVOKE_STATIC_RANGE);
        Dops.set(INVOKE_INTERFACE_RANGE);
        Dops.set(NEG_INT);
        Dops.set(NOT_INT);
        Dops.set(NEG_LONG);
        Dops.set(NOT_LONG);
        Dops.set(NEG_FLOAT);
        Dops.set(NEG_DOUBLE);
        Dops.set(INT_TO_LONG);
        Dops.set(INT_TO_FLOAT);
        Dops.set(INT_TO_DOUBLE);
        Dops.set(LONG_TO_INT);
        Dops.set(LONG_TO_FLOAT);
        Dops.set(LONG_TO_DOUBLE);
        Dops.set(FLOAT_TO_INT);
        Dops.set(FLOAT_TO_LONG);
        Dops.set(FLOAT_TO_DOUBLE);
        Dops.set(DOUBLE_TO_INT);
        Dops.set(DOUBLE_TO_LONG);
        Dops.set(DOUBLE_TO_FLOAT);
        Dops.set(INT_TO_BYTE);
        Dops.set(INT_TO_CHAR);
        Dops.set(INT_TO_SHORT);
        Dops.set(ADD_INT);
        Dops.set(SUB_INT);
        Dops.set(MUL_INT);
        Dops.set(DIV_INT);
        Dops.set(REM_INT);
        Dops.set(AND_INT);
        Dops.set(OR_INT);
        Dops.set(XOR_INT);
        Dops.set(SHL_INT);
        Dops.set(SHR_INT);
        Dops.set(USHR_INT);
        Dops.set(ADD_LONG);
        Dops.set(SUB_LONG);
        Dops.set(MUL_LONG);
        Dops.set(DIV_LONG);
        Dops.set(REM_LONG);
        Dops.set(AND_LONG);
        Dops.set(OR_LONG);
        Dops.set(XOR_LONG);
        Dops.set(SHL_LONG);
        Dops.set(SHR_LONG);
        Dops.set(USHR_LONG);
        Dops.set(ADD_FLOAT);
        Dops.set(SUB_FLOAT);
        Dops.set(MUL_FLOAT);
        Dops.set(DIV_FLOAT);
        Dops.set(REM_FLOAT);
        Dops.set(ADD_DOUBLE);
        Dops.set(SUB_DOUBLE);
        Dops.set(MUL_DOUBLE);
        Dops.set(DIV_DOUBLE);
        Dops.set(REM_DOUBLE);
        Dops.set(ADD_INT_2ADDR);
        Dops.set(SUB_INT_2ADDR);
        Dops.set(MUL_INT_2ADDR);
        Dops.set(DIV_INT_2ADDR);
        Dops.set(REM_INT_2ADDR);
        Dops.set(AND_INT_2ADDR);
        Dops.set(OR_INT_2ADDR);
        Dops.set(XOR_INT_2ADDR);
        Dops.set(SHL_INT_2ADDR);
        Dops.set(SHR_INT_2ADDR);
        Dops.set(USHR_INT_2ADDR);
        Dops.set(ADD_LONG_2ADDR);
        Dops.set(SUB_LONG_2ADDR);
        Dops.set(MUL_LONG_2ADDR);
        Dops.set(DIV_LONG_2ADDR);
        Dops.set(REM_LONG_2ADDR);
        Dops.set(AND_LONG_2ADDR);
        Dops.set(OR_LONG_2ADDR);
        Dops.set(XOR_LONG_2ADDR);
        Dops.set(SHL_LONG_2ADDR);
        Dops.set(SHR_LONG_2ADDR);
        Dops.set(USHR_LONG_2ADDR);
        Dops.set(ADD_FLOAT_2ADDR);
        Dops.set(SUB_FLOAT_2ADDR);
        Dops.set(MUL_FLOAT_2ADDR);
        Dops.set(DIV_FLOAT_2ADDR);
        Dops.set(REM_FLOAT_2ADDR);
        Dops.set(ADD_DOUBLE_2ADDR);
        Dops.set(SUB_DOUBLE_2ADDR);
        Dops.set(MUL_DOUBLE_2ADDR);
        Dops.set(DIV_DOUBLE_2ADDR);
        Dops.set(REM_DOUBLE_2ADDR);
        Dops.set(ADD_INT_LIT16);
        Dops.set(RSUB_INT);
        Dops.set(MUL_INT_LIT16);
        Dops.set(DIV_INT_LIT16);
        Dops.set(REM_INT_LIT16);
        Dops.set(AND_INT_LIT16);
        Dops.set(OR_INT_LIT16);
        Dops.set(XOR_INT_LIT16);
        Dops.set(ADD_INT_LIT8);
        Dops.set(RSUB_INT_LIT8);
        Dops.set(MUL_INT_LIT8);
        Dops.set(DIV_INT_LIT8);
        Dops.set(REM_INT_LIT8);
        Dops.set(AND_INT_LIT8);
        Dops.set(OR_INT_LIT8);
        Dops.set(XOR_INT_LIT8);
        Dops.set(SHL_INT_LIT8);
        Dops.set(SHR_INT_LIT8);
        Dops.set(USHR_INT_LIT8);
        Dops.set(INVOKE_POLYMORPHIC);
        Dops.set(INVOKE_POLYMORPHIC_RANGE);
        Dops.set(INVOKE_CUSTOM);
        Dops.set(INVOKE_CUSTOM_RANGE);
        Dops.set(CONST_METHOD_HANDLE);
        Dops.set(CONST_METHOD_TYPE);
    }
}

